services:
  - type: web
    name: pemb-spec-extractor-api
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: S3_ENDPOINT_URL
        sync: false
      - key: S3_ACCESS_KEY_ID
        sync: false
      - key: S3_SECRET_ACCESS_KEY
        sync: false
      - key: S3_BUCKET
        value: pemb-project-files
      - key: S3_REGION
        value: auto
      - key: CORS_ORIGINS
        sync: false
